# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lissto < Formula
  desc "Lissto CLI - Deploy and manage your stacks on Kubernetes"
  homepage "https://github.com/lissto-dev/cli"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lissto-dev/cli/releases/download/v0.1.2/cli_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "27f1857f02c18a49e495dbf51c6a17d7a8a20147f99890810b05c3f78b1a48dc"

      def install
        bin.install "lissto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lissto-dev/cli/releases/download/v0.1.2/cli_0.1.2_Darwin_arm64.tar.gz"
      sha256 "850e35d0ab83d59487ade6e387b0a9f43688be92ace342823a09c145e951ef3a"

      def install
        bin.install "lissto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lissto-dev/cli/releases/download/v0.1.2/cli_0.1.2_Linux_x86_64.tar.gz"
      sha256 "391258b99f76b939d0e9673dd6783193e914dd7cd3264a7c131bbb0f810a5eea"
      def install
        bin.install "lissto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lissto-dev/cli/releases/download/v0.1.2/cli_0.1.2_Linux_arm64.tar.gz"
      sha256 "b7cfaffb7056233c689827cc728f2637f1a7594a65ad471752ee706b505c32b6"
      def install
        bin.install "lissto"
      end
    end
  end

  test do
    system "#{bin}/lissto", "--version"
  end
end
