# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lissto < Formula
  desc "Lissto CLI - Deploy and manage your stacks on Kubernetes"
  homepage "https://github.com/lissto-dev/cli"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lissto-dev/cli/releases/download/v0.1.4/cli_0.1.4_darwin_amd64.tar.gz"
      sha256 "f648a2b4aafb7e184ae71873ccaffe26c15c0c43f08821e0b9e40f6625f363e0"

      def install
        bin.install "lissto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lissto-dev/cli/releases/download/v0.1.4/cli_0.1.4_darwin_arm64.tar.gz"
      sha256 "5b458378df0fb1727e159da97fe81f5c18fee41610e2a64c19eb13bd83493152"

      def install
        bin.install "lissto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lissto-dev/cli/releases/download/v0.1.4/cli_0.1.4_linux_amd64.tar.gz"
      sha256 "65a5c10256324911be318adbe6b5b32c87482892d0bf64a3bb1a02b255507a2f"
      def install
        bin.install "lissto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lissto-dev/cli/releases/download/v0.1.4/cli_0.1.4_linux_arm64.tar.gz"
      sha256 "40f45c91e55d7ad571e1523699b6fd8f51f907834fc17f15009076537feca285"
      def install
        bin.install "lissto"
      end
    end
  end

  test do
    system "#{bin}/lissto", "--version"
  end
end
